### PR TITLE
Add citation file.

### PR DESCRIPTION
**Pull request by aterenin**

### CODE REVIEW

**Comment by vabor112** [comment]
I suggest adding citation in CFF format. Then the "cite this repository" button will behave nicer: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

Important: don't forget `type: article` in CFF, otherwise bibtex entry will be `software` rather than `article`.

**Comment by aterenin** [comment]
How about we keep it as-is? The citation button supports BibTeX too - CFF is not the only choice. See for instance my thesis repo. From a user's point of view, almost everyone in machine learning uses BibTeX, so CFF is a less-optimal format in our situation.

**Comment by vabor112** [comment]
> so CFF is a less-optimal format in our situation

I disagree. Take a look at [this repo](https://github.com/igraph/rigraph), for example. If you click "Cite this repository', there's both a quick APA-style citation and a bibtex entry to copy, without the need to load a separate page.

If you don't want to bother, I can do this myself in two days.

**Comment by aterenin** [comment]
I also disagree. On that page, it requires more clicks for the user to get the bib entry. It also makes it more difficult for the user to get the citation directly from the package's source rather than from the GitHub website. Using .bib seems cleaner.

**Comment by vabor112** [comment]
I can't believe this is so difficult 🫤.

> On that page, it requires more clicks for the user to get the bib entry

No, there you click "cite this repository", then "BibTeX". It's 2 clicks.

With `.bib` file, you click "cite this repository", then "View citation file", then wait for a webpage to load. It's 2 clicks + page load. If you mean clicking on `CITATION.bib` in the tree, remember that you can always just copy the citation from `README`, which is zero clicks away, and also is right there in the package's source.

In any case, if you want to have a `.bib` file in the tree, we can keep it, but I think it makes all the sense to create a CFF to improve the UX of the "cite this repository" button. Granted they can co-exist.

**Review by stoprightthere — APPROVED** [review]
Great, we now have 3 (!) sources of the same info :)

When merging, I suggest squashing.

**Pull request merged**
